<html>
	<head>
		<title><?= $this->pageTitle ?></title>
		<script type="text/javascript" src="scripts/StandardWidgets.js"></script> 
		<script type="text/javascript" src="scripts/dojo-1.2.3/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
		<link href="http://o.aolcdn.com/dojo/1.0.0/dijit/themes/tundra/tundra.css" media="screen" rel="stylesheet" type="text/css"/>
		<link href="http://o.aolcdn.com/dojo/1.0.0/dojo/resources/dojo.css" media="screen" rel="stylesheet" type="text/css"/>
		<link href="styles/style.css" media="screen" rel="stylesheet" type="text/css"/>
		<scriptgroup />
		<stylegroup />
	</head>
	<body class="tundra">
		<header>
			<banner title="Sample Application Page" subtitle="Version 1.0" />
			<nav>
				<?php foreach($this->tabs as $link => $label) { ?>
					<navitem url="<?= $link ?>" <?= ($label == 'Example 1' ? 'current="true"' : '') ?>><?= $label ?></navitem>
				<?php } ?>
			</nav>
			<subnav>
				<?php foreach($this->subnavtabs as $link => $label) { ?>
					<navitem url="<?= $link ?>" <?= ($label == 'Example 1' ? 'current="true"' : '') ?>><?= $label ?></navitem>
				<?php } ?>
			</subnav>
		</header>
		<content>
			<panel label="My Panel" id="panel1" style="width: 500px; height: 145px;">
				<h3>Hi!</h3>
				<p>
					Here is some content 1.
				</p>
			</panel>
		
			<tabs style="margin-top: 10px; width: 500px; height: 150px;">
				<tab label="Tab 1" id="tab1">
					<h3>Hi!</h3>
					<p>
						Here is some content.
					</p>
				</tab>
				<tab label="Tab 2" id="tab2" selected="true">
					<h3>Hi!</h3>
					<p>
						Here is some content 2.
					</p>
				</tab>
				<tab label="Tab 3" id="tab3">
					<h3>Hi!</h3>
					<p>
						Here is some content 3.
					</p>
				</tab>
			</tabs>
			<dashboard handles="true" style="width: 50%; margin-top: 10px; border: 1px #666 solid; vertical-align: top;" zones="4">
				<panel label="Panel 1" id="panel2" collapsible="true" style="margin: 2px;">
					<h3>Hi!</h3>
					<p>
						Here is some content 1.
					</p>
				</panel>
				<panel label="Panel 2" id="panel3" collapsible="true" style="margin: 2px;">
					<h3>Hi!</h3>
					<p>
						Here is some content 2.
					</p>
				</panel>
				<panel label="Panel 3" id="panel4" collapsible="true" style="margin: 2px;">
					<h3>Hi!</h3>
					<p>
						Here is some content 3.
					</p>
				</panel>
			</dashboard>
			<tree style="margin-top: 10px; height: 200px; width: 300px;">
				<branch label="Branch">
					<branch label="Child Branch" id="childbranch1" >
						<leaf label="Leaf" id="leaf1" class="leaf" href="http://google.com" disabled="false" />
					</branch>
				</branch>
			</tree>
			<grid id="data-grid" style="margin-top: 20px;" width="500" height="200">
				<ghead>
					<gr>
						<gh width="200">Name</gh>
						<gh width="200">City</gh>
						<gh width="100">Gender</gh>
					</gr>
				</ghead>
				<gbody>
					<gr>
						<gd>Mike</gd>
						<gd>San Francisco</gd>
						<gd>Male</gd>
					</gr>
					<gr>
						<gd>Mia</gd>
						<gd>Seattle</gd>
						<gd>Female</gd>
					</gr>
					<gr>
						<gd>Brett</gd>
						<gd>Washington, DC</gd>
						<gd>Male</gd>
					</gr>
				</gbody>
			</grid>
			<fieldset style="margin-top: 20px">
				<legend>Test Form</legend>
				<text label="Name" size="20" />
				<password label="Password" size="20" />
				<file label="Resume" />
				<div class="form-element-container">
					<checkbox label="Remember Me" />
				</div>
				<submit value="Submit" />
				<button value="Button" />
			</fieldset>
		</content>
		<footer>
			<h6>Copyright 2009, 18th Street Software, LLC.</h6>
		</footer>
	</body>
</html>