<html>
	<head>
		<title><?= $this->pageTitle ?></title>
		<script type="text/javascript" src="scripts/StandardWidgets.js"></script> 
		<link href="styles/ext-2.2/css/ext-all.css" media="screen" rel="stylesheet" type="text/css"/>
		<link href="styles/ext-2.2/portal.css" media="screen" rel="stylesheet" type="text/css"/> 
		<link href="styles/reset.css" media="screen" rel="stylesheet" type="text/css"/> 
		<link href="styles/style.css" media="screen" rel="stylesheet" type="text/css"/>
		<scriptgroup />
		<stylegroup />
	</head>
	<body>
		<header>
			<banner title="Sample Application Page" subtitle="Version 1.0" />
			<nav>
				<?php foreach($this->tabs as $link => $label) { ?>
					<navitem url="<?= $link ?>"><?= $label ?></navitem>
				<?php } ?>
			</nav>
			<subnav>
				<?php foreach($this->subnavtabs as $link => $label) { ?>
					<navitem url="<?= $link ?>"><?= $label ?></navitem>
				<?php } ?>
			</subnav>
		</header>
		<content>
			<panel label="" id="panel1">
				<h3>Hi!</h3>
				<p>
					Here is some content 1.
				</p>
			</panel>
			<br />
			<p>text</p>
			<tabs default="tab1">
				<tab label="Tab 1" id="tab1">
					<h3>Hi!</h3>
					<p>
						Here is some content.
					</p>
				</tab>
				<tab label="Tab 2" id="tab2">
					<h3>Hi!</h3>
					<p>
						Here is some content 2.
					</p>
				</tab>
				<tab label="Tab 3" id="tab3">
					<h3>Hi!</h3>
					<p>
						Here is some content 3.
					</p>
				</tab>
			</tabs>
			<dashboard style="width: 50%; margin-top: 10px;">
				<column width=".3333">
					<panel label="Panel 1" id="panel2" embed="true" collapsible="true">
						<h3>Hi!</h3>
						<p>
							Here is some content 1.
						</p>
					</panel>
				</column>
				<column width=".3333">
					<panel label="Panel 2" id="panel3" embed="true" collapsible="true">
						<h3>Hi!</h3>
						<p>
							Here is some content 2.
						</p>
					</panel>
				</column>
				<column width=".3333">
					<panel label="Panel 3" id="panel4" embed="true" collapsible="true">
						<h3>Hi!</h3>
						<p>
							Here is some content 3.
						</p>
					</panel>
				</column>
			</dashboard>
			<tree style="margin-top: 10px; height: 500px; width: 300px;">
				<branch label="Branch">
					<branch label="Child Branch" id="childbranch1" >
						<leaf label="Leaf" id="leaf1" class="leaf" onclick="" href="http://google.com" disabled="false" />
					</branch>
				</branch>
			</tree>
			<grid id="data-grid" style="margin-top: 20px;">
				<ghead>
					<gr>
						<gh>
					</gr>
				</ghead>
			</grid>
		</content>
		<footer>
			<h6>Copyright 2009, 18th Street Software, LLC.</h6>
		</footer>
	</body>
</html>